(in-package :lem)

(define-color-theme "simple-theme" ()
  (:display-background-mode :light)
  (:foreground "black")
  (:background "white")
  (:inactive-window-background "light gray")
  (region :background "black" :foreground "white")
  (modeline :background "black" :foreground "white")
  (modeline-inactive :background "#101010" :foreground "#DFDFDF")
  (syntax-string-attribute :foreground nil)
  (syntax-comment-attribute :foreground nil :bold t)
  (syntax-keyword-attribute :foreground nil)
  (syntax-constant-attribute :foreground nil)
  (syntax-function-name-attribute :foreground nil)
  (syntax-variable-attribute :foreground nil)
  (syntax-builtin-attribute :foreground nil)
  (syntax-type-attribute :foreground nil)
  (lem/show-paren:showparen-attribute :foreground "white" :background "black"))
